simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
    
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 8.0, i: 1.0, d: 2.0}
